package com.mycompany.main;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class JournalPage extends javax.swing.JPanel {

    private JPanel journalListPanel;
    private JScrollPane scrollPane;
    private CustomButton writeButton;
    private JPanel writePanel;
    private CustomTextField textField;

    private static final String JOURNAL_FILE = "journals.json";
    
    public JournalPage() {
        initComponents();
        initCustomComponents();
        loadJournals();
    }

    private void initCustomComponents() {
    setLayout(new BorderLayout());

    // -------------------- Journal List Panel --------------------
    journalListPanel = new JPanel();
    journalListPanel.setLayout(new BoxLayout(journalListPanel, BoxLayout.Y_AXIS));

    scrollPane = new JScrollPane(journalListPanel);
    scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    scrollPane.setPreferredSize(new Dimension(830, 540));
    add(scrollPane, BorderLayout.CENTER);

    // -------------------- Write Button --------------------
    writeButton = new CustomButton();
    writeButton.setText("Write Journal");
    writeButton.setFillOriginal(new Color(100, 149, 237));
    writeButton.setFillOver(new Color(65, 105, 225));
    writeButton.setFillClick(new Color(30, 144, 255));
    writeButton.setPreferredSize(new Dimension(160, 50)); // Make button bigger
    writeButton.addActionListener(e -> showWritePanel());
    writeButton.setSlideDistance(0);

    // Panel to hold the button at top-right
    JPanel topPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
    topPanel.add(writeButton);
    add(topPanel, BorderLayout.NORTH);

// -------------------- Write Panel --------------------
writePanel = new JPanel(new BorderLayout());

// Wrapper panel to hold text field and save button
JPanel wrapper = new JPanel();
wrapper.setLayout(new BoxLayout(wrapper, BoxLayout.Y_AXIS));
wrapper.setAlignmentX(Component.CENTER_ALIGNMENT);

// TextField
textField = new CustomTextField();
textField.setColumns(40);
Dimension textDim = new Dimension(830, 480);
textField.setPreferredSize(textDim);
textField.setMinimumSize(textDim);
textField.setMaximumSize(textDim);
textField.setAlignmentX(Component.CENTER_ALIGNMENT);
wrapper.add(Box.createVerticalStrut(2)); 
wrapper.add(textField);
wrapper.add(Box.createVerticalStrut(0)); // spacing before button

// Save Button
CustomButton saveButton = new CustomButton();
saveButton.setText("Save Journal");
saveButton.setFillOriginal(new Color(60, 179, 113));
saveButton.setFillOver(new Color(34, 139, 34));
saveButton.setFillClick(new Color(0, 128, 0));
saveButton.setAlignmentX(Component.CENTER_ALIGNMENT);
saveButton.setSlideDistance(0);
saveButton.setPreferredSize(new Dimension(830, 30));
saveButton.addActionListener(e -> saveJournal());

wrapper.add(saveButton);
wrapper.add(Box.createVerticalGlue()); // push content up if space left

writePanel.add(wrapper, BorderLayout.NORTH); // keep at top


}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private void showWritePanel() {
    remove(scrollPane);                    // remove journal list
    add(writePanel, BorderLayout.CENTER);  // show write panel
    writeButton.setVisible(false);         // hide the top-right button
    revalidate();
    repaint();
    textField.setText("");
    textField.requestFocus();
}

private void showJournalListPanel() {
    remove(writePanel);
    add(scrollPane, BorderLayout.CENTER);
    writeButton.setVisible(true);          // show the top-right button again
    revalidate();
    repaint();
}

private void saveJournal() {
    String content = textField.getText().trim();
    if (content.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Journal is empty!", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String date = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());

    // Save to file
    try {
        FileWriter fw = new FileWriter(JOURNAL_FILE, true);
        BufferedWriter bw = new BufferedWriter(fw);
        PrintWriter out = new PrintWriter(bw);

        // Simple JSON-like format: {"date":"...","content":"..."}
        String escapedContent = content.replace("\"", "\\\"");
        out.println("{\"date\":\"" + date + "\",\"content\":\"" + escapedContent + "\"}");
        out.close();
    } catch (IOException e) {
        e.printStackTrace();
    }

    // Add to panel
    addJournalToList(date, content);
    showJournalListPanel();  // this will also make the write button visible again
}


    private void loadJournals() {
        File file = new File(JOURNAL_FILE);
        if (!file.exists()) return;

        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String line;
            while ((line = br.readLine()) != null) {
                // Parse simple JSON manually
                String date = extractValue(line, "date");
                String content = extractValue(line, "content");
                if (date != null && content != null) {
                    addJournalToList(date, content);
                }
            }
            br.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void addJournalToList(String date, String content) {
        JTextArea area = new JTextArea();
        area.setEditable(false);
        area.setLineWrap(true);
        area.setWrapStyleWord(true);
        area.setText("[" + date + "]\n" + content);
        area.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));

        journalListPanel.add(area);
        journalListPanel.add(Box.createRigidArea(new Dimension(0, 10)));
        journalListPanel.revalidate();
        journalListPanel.repaint();
    }

    private String extractValue(String jsonLine, String key) {
        String pattern = "\"" + key + "\":\"";
        int start = jsonLine.indexOf(pattern);
        if (start == -1) return null;
        start += pattern.length();
        int end = jsonLine.indexOf("\"", start);
        if (end == -1) return null;
        return jsonLine.substring(start, end).replace("\\\"", "\"");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
