package com.mycompany.main;

public class PagePanel extends javax.swing.JPanel {

    private Main main;
    
    public PagePanel(Main main) {
        this.main = main;
        initComponents();
        changeContent(new HomePage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBar = new javax.swing.JPanel();
        HomeButton = new com.mycompany.main.CustomButton();
        ProfileButton = new com.mycompany.main.CustomButton();
        JournalButton = new com.mycompany.main.CustomButton();
        content = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        sideBar.setBackground(new java.awt.Color(33, 118, 229));
        sideBar.setPreferredSize(new java.awt.Dimension(130, 540));

        HomeButton.setText("Home");
        HomeButton.setFillClick(new java.awt.Color(33, 118, 229));
        HomeButton.setFillOriginal(new java.awt.Color(33, 118, 229));
        HomeButton.setFillOver(new java.awt.Color(102, 204, 255));
        HomeButton.setSlideDistance(0);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        ProfileButton.setText("Profile");
        ProfileButton.setFillClick(new java.awt.Color(33, 118, 229));
        ProfileButton.setFillOriginal(new java.awt.Color(33, 118, 229));
        ProfileButton.setFillOver(new java.awt.Color(102, 204, 255));
        ProfileButton.setSlideDistance(0);
        ProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileButtonActionPerformed(evt);
            }
        });

        JournalButton.setText("Journal");
        JournalButton.setFillClick(new java.awt.Color(33, 118, 229));
        JournalButton.setFillOriginal(new java.awt.Color(33, 118, 229));
        JournalButton.setFillOver(new java.awt.Color(102, 204, 255));
        JournalButton.setSlideDistance(0);
        JournalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JournalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addComponent(JournalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addComponent(ProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(JournalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
        );

        content.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(830, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    public void changeContent(javax.swing.JPanel panel){
        content.removeAll();
        content.repaint();
        content.revalidate();

        content.add(panel);
        content.repaint();
        content.revalidate();
    }
    
    private void ProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileButtonActionPerformed
        changeContent(new ProfilePage());
    }//GEN-LAST:event_ProfileButtonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        changeContent(new HomePage());
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void JournalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JournalButtonActionPerformed
        changeContent(new JournalPage());
    }//GEN-LAST:event_JournalButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.main.CustomButton HomeButton;
    private com.mycompany.main.CustomButton JournalButton;
    private com.mycompany.main.CustomButton ProfileButton;
    private javax.swing.JPanel content;
    private javax.swing.JPanel sideBar;
    // End of variables declaration//GEN-END:variables
}
